BBBBBBB BBBBBBBBBBBBBBBBBBB

BBBB BBBB

BBBBB BBBBBBB

XXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXX gettext(u'Logged out successfully!') XXXXX
        XXXXX XXXXXXBBB BBBBBBBBBBBBBBXX gettext(u'Click here to go back to landing page') XXXXXXXX
    XXXXXX

XXXXXX

BBBBBBBB