BBBBBBB BBBBBBBBBBBBBBBBBBB

BBBB BBBB

BBBBB BBBBBBB

XXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXX

    XXX XXXXXXXXXXXXX gettext(u'Login') XXXXX

    BB BBBB
        BB BBBBBBBBBBBBBBBBBBBBB
            XXX gettext(u"Your account doesn't have access to this page. To proceed, please login with an account that has access.") XXXX
        BBBB
            XXX gettext(u'Please login to see this page.') XXXX
        BBBBB
    BBBBB

    BB BBBBBBBBBBB
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
             gettext(u"Your username and password didn't match. Please try again.") 
        XXXXXX
    BBBBB

    XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBXX
        BBBBBBBBBB

        BBB BBBBBB BB BBBBBBBBBBBBBBBBBB
            
        BBBBBB

        XXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXX

        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XX

        XXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXX gettext(u'Login') X XX
        XXXXXX
    XXXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBXX gettext(u"Don't have an account?") XXXXXXXX
        XX XXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBXX gettext(u'Reset password') XXXXXXXX
    XXXXXX

XXXXXX

BBBBBBBB