# Generated by Django 3.0.8 on 2020-08-17 06:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_imageupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
