# Generated by Django 3.0.8 on 2020-08-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_auto_20200804_1021'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='collectionstar',
            constraint=models.UniqueConstraint(fields=('user', 'collection'), name='collection_unique_key'),
        ),
        migrations.AddConstraint(
            model_name='documentstar',
            constraint=models.UniqueConstraint(fields=('user', 'document'), name='document_unique_key'),
        ),
    ]
