BBBBBBB BBBBBBBBBBBBBBBBBBB

BBBB BBBB

BBBBB BBBBBBB

XXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXX

    XXX XXXXXXXXXXXXX gettext(u'Sign-up') XXXXX

    BB BBBB
        BB BBBBBBBBBBBBBBBBBBBBB
            XXX gettext(u"Your account doesn't have access to this page. To proceed, please login with an account that has access.") XXXX
        BBBB
            XXX gettext(u'Please login to see this page.') XXXX
        BBBBB
    BBBBB

    BB BBBBBBBBBBB
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
             gettext(u'There was an error while signing up.') 
        XXXXXX
    BBBBB

    XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBXX
        BBBBBBBBBB

        XXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXX

        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XX

        XXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXX gettext(u'Create account') X XX
        XXXXXX

    XXXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBXX gettext(u'Already have an account? Log in here.') XXXXXXXX
    XXXXXX

XXXXXX

BBBBBBBB